#!/usr/bin/env bash
# ============================================================================
# install-postgres-mcp.sh
# Instala el MCP de PostgreSQL para Opencode con auto-detección de DB
# desde Openbravo.properties (proyectos Etendo/Openbravo).
#
# Uso:
#   ./install-postgres-mcp.sh                          # interactivo
#   ./install-postgres-mcp.sh /ruta/al/proyecto        # con path al proyecto
#
# Requisitos: uv, jq, bash 4+
# ============================================================================

set -euo pipefail

# --- Colores ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
die()   { error "$*"; exit 1; }

# --- Verificar dependencias ---
check_deps() {
  local missing=()
  command -v uv  >/dev/null 2>&1 || missing+=("uv")
  command -v jq  >/dev/null 2>&1 || missing+=("jq")
  command -v bash >/dev/null 2>&1 || missing+=("bash")

  if [[ ${#missing[@]} -gt 0 ]]; then
    die "Faltan dependencias: ${missing[*]}\n  Instalalas antes de continuar:\n  - uv:  curl -LsSf https://astral.sh/uv/install.sh | sh\n  - jq:  sudo apt install jq  (o brew install jq)"
  fi
  ok "Dependencias verificadas (uv, jq, bash)"
}

# --- Resolver path del proyecto ---
resolve_project_path() {
  local project_path="${1:-}"

  if [[ -z "$project_path" ]]; then
    echo ""
    info "¿Cuál es la ruta absoluta del proyecto Etendo/Openbravo?"
    info "(debe contener config/Openbravo.properties)"
    read -rp "> " project_path
  fi

  # Expandir ~ si lo usaron
  project_path="${project_path/#\~/$HOME}"

  # Validar
  if [[ ! -d "$project_path" ]]; then
    die "El directorio no existe: $project_path"
  fi

  if [[ ! -f "$project_path/config/Openbravo.properties" ]]; then
    die "No se encontró config/Openbravo.properties en: $project_path"
  fi

  echo "$project_path"
}

# --- Verificar conectividad a la DB ---
test_db_connection() {
  local props_file="$1"

  get_prop() {
    grep -E "^${1}=" "$props_file" | head -1 | cut -d'=' -f2- | tr -d '[:space:]'
  }

  local bbdd_url bbdd_sid bbdd_user bbdd_password host_port
  bbdd_url=$(get_prop "bbdd.url")
  bbdd_sid=$(get_prop "bbdd.sid")
  bbdd_user=$(get_prop "bbdd.user")
  bbdd_password=$(get_prop "bbdd.password")
  host_port=$(echo "$bbdd_url" | sed 's|jdbc:postgresql://||')

  local uri="postgresql://${bbdd_user}:${bbdd_password}@${host_port}/${bbdd_sid}"

  info "Conexión detectada: postgresql://${bbdd_user}:****@${host_port}/${bbdd_sid}"

  if command -v psql >/dev/null 2>&1; then
    if psql "$uri" -c "SELECT 1" >/dev/null 2>&1; then
      ok "Conexión a la base de datos verificada"
    else
      warn "No se pudo conectar a la DB. Verificá que PostgreSQL esté corriendo y las credenciales sean correctas."
      warn "El MCP se instalará igual, pero no funcionará hasta que la DB sea accesible."
    fi
  else
    warn "psql no está instalado. No se pudo verificar la conexión (se instalará igual)."
  fi
}

# --- Instalar el wrapper script ---
install_wrapper() {
  local scripts_dir="$HOME/.config/opencode/scripts"
  local wrapper_path="$scripts_dir/postgres-mcp-wrapper.sh"

  mkdir -p "$scripts_dir"

  cat > "$wrapper_path" << 'WRAPPER_EOF'
#!/usr/bin/env bash
# postgres-mcp-wrapper.sh
# Reads DB connection from Openbravo.properties and launches postgres-mcp
# Auto-generated by install-postgres-mcp.sh

set -euo pipefail

# --- Resolve project root ---
find_properties() {
  local dir="${1:-.}"
  local props_file="$dir/config/Openbravo.properties"
  if [[ -f "$props_file" ]]; then
    echo "$props_file"
    return 0
  fi
  return 1
}

PROPS_FILE=""
if find_properties "." >/dev/null 2>&1; then
  PROPS_FILE=$(find_properties ".")
elif [[ -n "${ETENDO_SOURCE_PATH:-}" ]] && find_properties "$ETENDO_SOURCE_PATH" >/dev/null 2>&1; then
  PROPS_FILE=$(find_properties "$ETENDO_SOURCE_PATH")
else
  echo "ERROR: Cannot find config/Openbravo.properties" >&2
  echo "Set ETENDO_SOURCE_PATH or run from project root" >&2
  exit 1
fi

# --- Parse properties ---
get_prop() {
  local key="$1"
  grep -E "^${key}=" "$PROPS_FILE" | head -1 | cut -d'=' -f2- | tr -d '[:space:]'
}

BBDD_URL=$(get_prop "bbdd.url")
BBDD_SID=$(get_prop "bbdd.sid")
BBDD_USER=$(get_prop "bbdd.user")
BBDD_PASSWORD=$(get_prop "bbdd.password")

# Extract host:port from jdbc URL (jdbc:postgresql://host:port)
HOST_PORT=$(echo "$BBDD_URL" | sed 's|jdbc:postgresql://||')

# Build PostgreSQL URI
export DATABASE_URI="postgresql://${BBDD_USER}:${BBDD_PASSWORD}@${HOST_PORT}/${BBDD_SID}"

# --- Launch postgres-mcp ---
exec uv run postgres-mcp --access-mode=unrestricted
WRAPPER_EOF

  chmod +x "$wrapper_path"
  ok "Wrapper instalado en: $wrapper_path"
  echo "$wrapper_path"
}

# --- Inyectar config en opencode.json ---
inject_opencode_config() {
  local project_path="$1"
  local wrapper_path="$2"
  local config_file="$HOME/.config/opencode/opencode.json"

  # Si no existe opencode.json, crear uno mínimo
  if [[ ! -f "$config_file" ]]; then
    warn "No se encontró opencode.json, creando uno nuevo..."
    mkdir -p "$(dirname "$config_file")"
    echo '{}' > "$config_file"
  fi

  # Verificar que es JSON válido
  if ! jq empty "$config_file" 2>/dev/null; then
    die "El archivo opencode.json no es JSON válido: $config_file"
  fi

  # Verificar si ya existe el MCP postgres
  if jq -e '.mcp.postgres' "$config_file" >/dev/null 2>&1; then
    warn "Ya existe una configuración de 'postgres' en opencode.json"
    read -rp "¿Querés sobreescribirla? (s/N): " overwrite
    if [[ "${overwrite,,}" != "s" && "${overwrite,,}" != "si" && "${overwrite,,}" != "sí" && "${overwrite,,}" != "y" && "${overwrite,,}" != "yes" ]]; then
      info "Instalación cancelada. La config existente se mantiene."
      return 0
    fi
  fi

  # Inyectar la config usando jq
  local tmp_file
  tmp_file=$(mktemp)

  jq --arg wrapper "$wrapper_path" \
     --arg source_path "$project_path" \
     '.mcp.postgres = {
        "type": "local",
        "enabled": true,
        "command": ["bash", $wrapper],
        "environment": {
          "ETENDO_SOURCE_PATH": $source_path
        }
      }' "$config_file" > "$tmp_file"

  mv "$tmp_file" "$config_file"
  ok "Configuración inyectada en: $config_file"
}

# ============================================================================
# MAIN
# ============================================================================
main() {
  echo ""
  echo -e "${CYAN}╔══════════════════════════════════════════════════════╗${NC}"
  echo -e "${CYAN}║  Instalador MCP PostgreSQL para Opencode            ║${NC}"
  echo -e "${CYAN}║  Auto-detección desde Openbravo.properties          ║${NC}"
  echo -e "${CYAN}╚══════════════════════════════════════════════════════╝${NC}"
  echo ""

  # 1. Check deps
  check_deps

  # 2. Resolve project path
  local project_path
  project_path=$(resolve_project_path "${1:-}")
  ok "Proyecto encontrado: $project_path"

  # 3. Test DB connection
  test_db_connection "$project_path/config/Openbravo.properties"

  # 4. Install wrapper script
  local wrapper_path
  wrapper_path=$(install_wrapper)

  # 5. Inject into opencode.json
  inject_opencode_config "$project_path" "$wrapper_path"

  # 6. Done
  echo ""
  echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║  ✓ Instalación completada                          ║${NC}"
  echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
  echo ""
  info "Archivos creados/modificados:"
  info "  - $wrapper_path"
  info "  - $HOME/.config/opencode/opencode.json"
  echo ""
  info "Para activar, reiniciá Opencode."
  info "Para cambiar de proyecto, volvé a correr el instalador con la nueva ruta."
  echo ""
}

main "$@"
